name: Generate Posts

on:
  schedule:
    - cron: '0 17 * * *'  # Runs daily at 17:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Uses the latest Python 3 version

      - name: Install dependencies
        run: |
          cd deepseek-posts
          pip install requests  # Install required dependencies

      - name: Run script
        run: |
          cd deepseek-posts
          python generate_posts.py
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-generate posts [$(date -u)]" || echo "No changes to commit"
          git push
